In [3]:
import numpy as np
import matlab.engine
# from anp_alg_matlab import AnPAlgorithmMatlab
from anp_alg import AnPAlgorithmPython, AnPAlgorithmMatlab, NONAPPAlgorithm, APPAlgorithm
from sonar_data_generator import SonarDataGenerator
from pathlib import Path
import os

from pathlib import Path

script_dir = Path(".")  # 当前目录
# 或者
nonapp_algorithm = NONAPPAlgorithm()




Start matlab engine, ANP module successfully initialized!


In [7]:

# 初始化参数

# P_W = np.array([[ 6.3723361 ,  4.5240402 ,  6.76254577,  6.25698193,  7.79260445,
#      6.72762702,  7.60267654,  7.08325777,  7.66213854,  7.23866499,
#      3.50257951,  6.4859005 ,  7.71081349,  5.81442691,  3.34292972,
#      5.00638702,  7.20522162,  4.29802294,  7.5583895 ,  6.42820651],
#    [-2.41570381, -0.69241184,  0.03362135, -0.81518972, -0.01676097,
#     -0.46288979, -1.31933768, -0.73648026, -0.35025381, -2.76620607,
#     -0.11115857, -0.76333301,  0.69313454, -1.26736277, -0.87691552,
#      0.12607952, -2.14465185,  0.02662272,  1.64634791,  1.31753699],
#    [-0.5415008 , -0.88246241, -0.11896007, -0.28181641, -0.90820135,
#     -1.2712701 , -0.28216007, -1.4478447 , -1.30231427,  0.30042688,
#     -0.54460507, -0.43337675, -0.42835824, -0.10344146, -0.4873707 ,
#     -1.09733627, -0.60270704, -0.47601693, -0.47785228, -0.45450962]])
# T = np.array([[ 0.98006778,  0.19166309,  0.05227235,  1.99314574],
#    [-0.19820337,  0.96123914,  0.19166309, -0.20221549],
#    [-0.01351149, -0.19820337,  0.98006778, -0.49885762],
#    [ 0.        ,  0.        ,  0.        ,  1.        ]])

# P_W = np.array([[ 2.13603473, -0.77186602,  1.95072114,  1.82645702,  0.80637312,
#      0.34877479,  1.43712997,  1.12189889,  1.95998657,  0.54235911,
#      1.3069241 , -0.50389582, -0.77042562,  0.56313092,  2.09759974,
#      1.93175828,  0.97354203,  1.29132247,  2.18199611,  0.91832501,
#      1.60884869, -0.6045416 ,  2.45790458, -0.15580471,  1.31191647,
#     -0.9142952 ,  2.26811886,  2.21745372, -0.04960047,  1.02438521,
#      1.28548098,  2.00271249,  0.90937901],
#    [ 1.6240803 ,  0.60711432,  1.76001179,  4.04454041,  2.19236112,
#      0.5548203 ,  0.32810998,  0.69382906,  2.48453283,  1.49465704,
#      3.06561542,  3.15025473,  2.14143443,  2.99997115,  4.09572172,
#      0.40185145,  3.47797823,  0.44462281,  0.18353406,  1.21580398,
#      2.54795504,  1.46164775,  1.08357716,  2.23380876,  2.69423199,
#      2.478338  ,  1.88500488,  1.7469312 ,  1.33389342,  4.6142211 ,
#     -0.0169981 ,  0.15571359,  4.31394911],
#    [-1.36646855, -0.03994431,  0.15434559,  0.09593417, -0.25782672,
#     -0.38742959, -0.24006221, -0.15651231, -0.18151858, -0.71256626,
#     -0.83193976,  0.43299642, -0.08076227,  0.12128959,  0.3754721 ,
#     -0.86207271,  0.56393188, -0.48081446, -0.20747855, -0.77819484,
#     -1.04896271, -0.43491939, -0.75536293,  0.19425119, -0.68284667,
#      0.39668149,  0.18036377, -1.16874087, -0.45922306, -0.33221188,
#     -1.37119341, -1.44178295,  0.51926494]])
# T = np.array([[ 0.98013292, -0.12185598,  0.15649465, -3.15206827],
#    [ 0.14159372,  0.98239622, -0.12185598,  1.4993604 ],
#    [-0.13889087,  0.14159372,  0.98013292,  0.35867805],
#    [ 0.        ,  0.        ,  0.        ,  1.        ]])

# P_W = np.array([[-0.73551238, -0.78118074, -1.69086969,  1.82645702,  1.61762846,
#      0.753883  ,  0.95702285,  0.3082487 , -0.50389582, -0.77042562,
#     -1.34752023,  0.56313092,  2.09759974, -0.05106884,  0.97354203,
#      2.0338192 , -1.25295126,  1.18398035, -0.15580471,  0.6671564 ,
#      0.5833928 , -0.9142952 ,  0.96047026,  0.94290197, -0.12518187,
#      1.02438521, -2.12233973, -0.75305557,  0.90937901],
#    [ 5.07160997,  4.06462431,  4.40920782,  4.04454041,  4.09644222,
#      2.31490397,  1.37838936,  4.73850679,  3.15025473,  2.14143443,
#      4.61606884,  2.99997115,  4.09572172,  0.65428174,  3.47797823,
#      4.52106762,  3.06919909,  3.59053254,  2.23380876,  4.95108843,
#      3.78203821,  2.478338  ,  4.65014696,  3.49452162,  3.91423082,
#      4.6142211 ,  4.51770592,  4.44417667,  4.31394911],
#    [-0.41982976, -0.38334644, -0.17856155,  0.09593417,  0.93814778,
#      0.58545303,  0.74550223,  0.71726167,  0.43299642, -0.08076227,
#      0.70441121,  0.12128959,  0.3754721 ,  0.52398193,  0.56393188,
#      0.53701097,  0.63171345,  1.01903784,  0.19425119,  0.08018826,
#      1.04325831,  0.39668149, -0.4360598 ,  1.08682835,  0.48751777,
#     -0.33221188, -0.92763418,  0.65935677,  0.51926494]])
# T = np.array([[-4.44089210e-16, -9.95496806e-01, -9.47950939e-02,
#      0.00000000e+00],
#    [ 9.99506619e-01, -2.97740981e-03,  3.12674616e-02,
#     -5.27963268e-01],
#    [-3.14089020e-02, -9.47483238e-02,  9.95005646e-01,
#      4.05062356e-01],
#    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
#      1.00000000e+00]])

P_W = np.array([[ 3.39461163,  1.39550166,  1.40684254,  0.74243717,  2.90571484,
        1.66751495,  1.06152158,  2.55713872,  3.63340226,  1.83619628,
        4.43347954,  2.54160729,  1.45648787,  0.9989926 ,  3.158429  ,
        1.98502214,  2.30279989,  1.99917682,  0.33536854,  1.02929976,
        2.0769054 ,  2.2390387 ,  1.28009858,  2.49243876,  1.88864529],
    [-3.83726733, -4.99174544, -1.90155744, -3.72639523, -4.36980523,
    -1.35429607, -3.12773574, -3.06542161, -3.91527822, -3.59780313,
    -4.46925097, -2.86482133, -3.57781254, -3.70633725, -4.86986645,
    -4.58842932, -4.83047604, -4.73959574, -4.32062428, -3.99266059,
    -1.65911354, -2.69220341, -3.77607002, -4.55296597, -4.18078314],
    [ 0.42368991, -0.23083743,  0.58751142,  0.01049521,  0.76560405,
        0.16558379, -0.41846748,  0.62141558, -0.37522612, -0.05664566,
        0.56119596, -0.03302974, -0.25989743, -0.63983399,  0.13457851,
    -0.2048321 ,  0.92602874,  0.43819447,  0.25120063,  0.86600469,
        0.51760116,  0.36589892,  0.04717307,  0.93970545,  0.89948555]])
T = np.array([[-4.44089210e-16,  9.98860050e-01, -4.77346822e-02,
        2.31591485e+00],
    [-9.96142649e-01, -4.18865332e-03, -8.76486083e-02,
        7.47097874e-01],
    [-8.77486373e-02,  4.75505528e-02,  9.95007096e-01,
        5.47752829e-01],
    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        1.00000000e+00]])
R_SW = T[0:3, 0:3]
t_S = T[0:3, 3].reshape(-1)



# 模拟生成 P_SI 和 P_SI_Noise 数据
data_generator = SonarDataGenerator(P_W, R_SW, t_S)
P_S, P_SI, P_SI_Noise = data_generator.generate_data()

P_SI_Noise2 = np.array([[ 4.58286766,  5.78935835,  2.65179153,  4.50379732,  5.11728534,
     2.13266321,  3.98069979,  3.81186324,  4.7575711 ,  4.38556521,
     5.22461167,  3.65906632,  4.39520347,  4.59383842,  5.63169149,
     5.38750068,  5.59033278,  5.48875972,  5.07932089,  4.75579452,
     2.40719166,  3.44423172,  4.54991702,  5.31291568,  4.94313751],
   [ 1.09207731, -0.93307222, -0.90080324, -1.578684  ,  0.6256945 ,
    -0.65884008, -1.29438422,  0.26185316,  1.3003841 , -0.49020173,
     2.09454449,  0.21355221, -0.88201084, -1.36909062,  0.84551766,
    -0.34437926,  0.02860032, -0.29924541, -1.97304973, -1.2666489 ,
    -0.23083691, -0.07109301, -1.03962724,  0.22001093, -0.39464513]])



print("When there is no noise\n")
t_s_cal, R_sw_cal = nonapp_algorithm.compute_t_R(P_SI_Noise, P_W, R_SW)
print("NONAPP R error: ", nonapp_algorithm.estimate_accuracy(R_SW))
print("NONAPP t error: ", np.linalg.norm(t_s_cal.T-t_S))


print("\nWhen data has noise\n")
t_s_cal2, R_sw_cal2 = nonapp_algorithm.compute_t_R(P_SI_Noise2, P_W, R_SW)
print("NONAPP R error: ", nonapp_algorithm.estimate_accuracy(R_SW))
print("NONAPP t error: ", np.linalg.norm(t_s_cal2.T-t_S))
print("====================================")
print()



When there is no noise

NONAPP R error:  (array([ 0.066991  ,  0.02146629, -1.00210487]), 3.1316501456344894)
NONAPP t error:  0.005100417898588358

When data has noise

NONAPP R error:  (array([1.25241513e+12, 4.92815490e+12, 6.12338208e+13]), 3.141592653589793)
NONAPP t error:  0.1445884643161615



In [8]:
print(t_S)
t_s_cal

[2.31591485 0.74709787 0.54775283]


array([[2.32096146],
       [0.74711844],
       [0.5470142 ]])

In [9]:
print(R_SW)
R_sw_cal

[[-4.44089210e-16  9.98860050e-01 -4.77346822e-02]
 [-9.96142649e-01 -4.18865332e-03 -8.76486083e-02]
 [-8.77486373e-02  4.75505528e-02  9.95007096e-01]]


array([[-6.41657584e-04, -9.95953528e-01, -8.76013626e-02],
       [ 9.99045128e-01, -5.15901532e-03,  4.77951412e-02],
       [-4.80536763e-02, -8.74870464e-02,  9.95005831e-01]])

In [ ]:
R_SW =

   -0.0000    0.9989   -0.0477
   -0.9961   -0.0042   -0.0876
   -0.0877    0.0476    0.9950


t_S =

    2.3159
    0.7471
    0.5478